import { ElementRef, QueryList, AfterViewInit, OnInit, OnDestroy, NgZone, ChangeDetectorRef } from '@angular/core';
import { PdfAnnotatorConfig } from './tokens';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { ModalController, ToastController, AlertController } from '@ionic/angular';
import { HttpClient } from '@angular/common/http';
import { PdfManagerService, PdfHistoryEntry } from './pdf-manager.service';
interface TextBox {
    id: string;
    page: number;
    zIndex?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    text: string;
    color: string;
    fontSize: number;
    bold: boolean;
    italic: boolean;
    align: 'left' | 'center' | 'right';
}
interface ImageStamp {
    id: string;
    page: number;
    zIndex?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    dataUrl: string;
    markType?: 'check' | 'cross' | 'dot';
    markColor?: string;
}
interface ShapeStamp {
    id: string;
    page: number;
    zIndex?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    type: 'rect' | 'circle' | 'arrow' | 'line';
    strokeColor: string;
    strokeWidth: number;
    viewWidth: number;
    fillColor?: string;
    startFracX: number;
    startFracY: number;
    endFracX: number;
    endFracY: number;
}
interface SignatureStamp {
    id: string;
    page: number;
    zIndex?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    dataUrl: string;
    digitalId?: string;
    signDate?: string;
    signTime?: string;
}
interface DateStamp {
    id: string;
    page: number;
    zIndex?: number;
    x: number;
    y: number;
    text: string;
    color: string;
    fontSize: number;
}
interface PdfFormField {
    id: string;
    page: number;
    zIndex?: number;
    type: 'text' | 'checkbox' | 'radio';
    x: number;
    y: number;
    width: number;
    height: number;
    fieldName: string;
    radioGroupName?: string;
    fontSize?: number;
    borderVisible?: boolean;
}
interface SavedSignature {
    id: number;
    user_id: string;
    signature_name: string;
    signature_data: string;
    is_default: boolean;
    created_at: string;
    updated_at: string;
}
export declare type ToolMode = 'none' | 'draw' | 'eraser' | 'highlight' | 'shape' | 'text' | 'signature' | 'date' | 'mark' | 'formfield';
export declare type ResizeDirection = 'n' | 's' | 'e' | 'w' | 'ne' | 'nw' | 'se' | 'sw';
export declare class PdfAnnotatorModalComponent implements OnInit, AfterViewInit, OnDestroy {
    private modalCtrl;
    private http;
    private zone;
    private toastCtrl;
    private alertCtrl;
    private cdr;
    private sanitizer;
    private pdfSvc;
    pdfUrl: string;
    fileName?: string;
    canManageGuide: boolean;
    pdfCanvases: QueryList<ElementRef<HTMLCanvasElement>>;
    annotCanvases: QueryList<ElementRef<HTMLCanvasElement>>;
    fileInputRef: ElementRef<HTMLInputElement>;
    viewerContainerRef: ElementRef<HTMLDivElement>;
    contextMenu: {
        show: boolean;
        x: number;
        y: number;
        targetId: string;
        targetType: string;
    };
    toolMode: ToolMode;
    shapeType: 'rect' | 'circle' | 'arrow' | 'line';
    showShapeMenu: boolean;
    showShapeDropdown: boolean;
    shapeNoStroke: boolean;
    shapeStrokeColor: string;
    shapeFillColor: string;
    shapeFillEnabled: boolean;
    shapeStrokeSize: number;
    readonly shapeColorSwatches: string[];
    readonly shapeFillSwatches: string[];
    brushColor: string;
    brushSize: number;
    highlightColor: string;
    highlightSize: number;
    eraserSize: number;
    pageNo: number;
    pageCount: number;
    private readonly PAGE_CHUNK;
    loadedUntilPage: number;
    isLoadingChunk: boolean;
    zoom: number;
    viewMode: 'single' | 'continuous';
    pages: number[];
    isLoading: boolean;
    loadingMessage: string;
    saveProgress: number;
    private renderingPages;
    private renderedPages;
    textBoxes: TextBox[];
    imageStamps: ImageStamp[];
    shapeStamps: ShapeStamp[];
    signatureStamps: SignatureStamp[];
    dateStamps: DateStamp[];
    pdfFormFields: PdfFormField[];
    private formFieldCounter;
    activeFormFieldId: string | null;
    showSignaturePad: boolean;
    showSignaturePicker: boolean;
    showPreviewOverlay: boolean;
    previewUrl: SafeResourceUrl | null;
    previewPages: string[];
    previewIsFiltered: boolean;
    previewTotalPages: number;
    isLoadingAllPreview: boolean;
    pageThumbnails: string[];
    showThumbnails: boolean;
    private lastSavedBlob;
    private lastSavedFileName;
    signatureCanvasRef: ElementRef<HTMLCanvasElement>;
    private signatureCtx;
    private isDrawingSignature;
    private signaturePoints;
    private signatureStrokes;
    private bufferCanvas;
    signaturePenColor: string;
    signaturePenSize: number;
    markType: 'check' | 'cross' | 'dot';
    formFieldType: 'text' | 'checkbox' | 'radio';
    markColor: string;
    markSize: number;
    showMarkOptions: boolean;
    dateColor: string;
    dateFontSize: number;
    showDateOptions: boolean;
    toggleDateOptions(): void;
    addDateStampAndShowOptions(): void;
    setDateColor(color: string): void;
    changeDateFontSize(delta: number): void;
    savedSignatures: SavedSignature[];
    isLoadingSignatures: boolean;
    userId: string;
    userName: string;
    documentId: number | null;
    detailId: any;
    edocId: any;
    isCancelMode: boolean;
    showDigitalId: boolean;
    signatureFileInputRef: ElementRef<HTMLInputElement>;
    thumbFileInputRef: ElementRef<HTMLInputElement>;
    thumbInsertIndex: number;
    thumbDropdownTargetIndex: number;
    showUserGuidePanel: boolean;
    isLoadingGuide: boolean;
    isEditingGuide: boolean;
    userGuideContent: string;
    tempGuideContent: string;
    thumbDropdownTop: number;
    private thumbInsertAtIndex;
    showHistoryPanel: boolean;
    historyEntries: PdfHistoryEntry[];
    isLoadingHistory: boolean;
    /** Log an action to the ruts-pdf history API (fire-and-forget) */
    private logHistory;
    toggleHistoryPanel(): void;
    private loadHistoryFromApi;
    getHistoryActionIcon(type: string): string;
    getHistoryActionLabel(type: string): string;
    showInsertMenu: boolean;
    showThumbInsertMenu: boolean;
    insertOrientation: 'portrait' | 'landscape';
    private pageHistoryStack;
    get canUndoPageOp(): boolean;
    private savePageSnapshot;
    undoPageOp(): Promise<void>;
    private strokes;
    private shapes;
    private redoStack;
    private activeStroke;
    private activeShape;
    private activeCanvasRect;
    private activePointerId;
    activeObjectId: string | null;
    activeObjectType: 'text' | 'shape' | 'image' | 'signature' | 'date' | null;
    private activePointerType;
    private renderRequested;
    private isRenderingAll;
    private renderDebounceTimer;
    private isDragging;
    private dragTextBoxId;
    private dragOffsetX;
    private dragOffsetY;
    private isResizing;
    private resizeTextBoxId;
    private isDraggingImage;
    private dragImageId;
    private isResizingImage;
    private resizeImageId;
    private isDraggingShape;
    private dragShapeId;
    private isResizingShape;
    private resizeShapeId;
    private resizeObserver;
    private isScrollNavigating;
    private basePdfBytes;
    /** PDF page aspect ratios (width/height) per page number, populated at load time */
    private pdfPageAspects;
    /** PDF page rotations (0/90/180/270) per page number, populated at load time from pdf-lib */
    private pdfPageRotations;
    revNo: number;
    private pdfDocProxy;
    private currentViewport;
    textColor: string;
    textFontSize: number;
    pendingSignatureDataUrl: string | null;
    activeTextBoxId: string | null;
    get activeTextBox(): TextBox | null;
    close(): void;
    get drawMode(): boolean;
    get eraserMode(): boolean;
    get highlightMode(): boolean;
    get shapeMode(): boolean;
    get textPlaceMode(): boolean;
    private signaturesApiUrl;
    private pdfWorkerSrc;
    constructor(modalCtrl: ModalController, http: HttpClient, zone: NgZone, toastCtrl: ToastController, alertCtrl: AlertController, cdr: ChangeDetectorRef, sanitizer: DomSanitizer, pdfSvc: PdfManagerService, config: PdfAnnotatorConfig | null);
    ngOnInit(): void;
    private readonly SETTINGS_KEY;
    private saveSettings;
    private loadSettings;
    get visibleTextBoxes(): TextBox[];
    get visibleImageStamps(): ImageStamp[];
    get visibleSignatures(): SignatureStamp[];
    get visibleDateStamps(): DateStamp[];
    getTextBoxesForPage(p: number): TextBox[];
    getImageStampsForPage(p: number): ImageStamp[];
    getRegularImageStampsForPage(p: number): ImageStamp[];
    getMarkStampsForPage(p: number): ImageStamp[];
    getShapeStampsForPage(p: number): ShapeStamp[];
    getSignatureStampsForPage(p: number): SignatureStamp[];
    getDateStampsForPage(p: number): DateStamp[];
    getMarkSvgContent(markType: string | undefined, color: string | undefined): string;
    /** Lock screen orientation to portrait while annotating */
    private lockOrientation;
    /** Unlock screen orientation when leaving the annotator */
    private unlockOrientation;
    ngAfterViewInit(): Promise<void>;
    private syncToolModeStyles;
    ngOnDestroy(): void;
    onDocumentPointerDown(event: any): void;
    handleKeyboard(event: KeyboardEvent): void;
    exitAllModes(): void;
    toggleUserGuide(e?: Event): void;
    fetchGuideData(): void;
    editGuide(): void;
    cancelEditGuide(): void;
    saveGuide(): void;
    closeContextMenu(): void;
    onContextMenu(e: MouseEvent, id: string, type: string): void;
    private getContextTargetObject;
    private getAllAnnotationsZIndices;
    contextBringToFront(): void;
    contextBringForward(): void;
    contextSendBackward(): void;
    contextSendToBack(): void;
    deleteContextMenuTarget(): void;
    private loadPdfBytesAndInitPdfjs;
    generateThumbnails(): Promise<void>;
    private generateThumbnailsRange;
    loadNextChunk(): Promise<void>;
    goToPage(pageNum: number): void;
    toggleThumbnails(): void;
    insertBlankPage(where: 'before' | 'after'): Promise<void>;
    deletePage(): Promise<void>;
    private doDeletePage;
    toggleThumbInsert(idx: number, event?: MouseEvent): void;
    /** Insert a blank page at `afterIndex` (0 = before page 1, n = after page n) */
    insertAtThumb(afterIndex: number, orientation: 'portrait' | 'landscape'): Promise<void>;
    triggerThumbFileUpload(afterIndex: number): void;
    onThumbFileSelected(event: Event): Promise<void>;
    movePageToIndex(pageNum: number, direction: 'up' | 'down'): Promise<void>;
    deleteSpecificPage(pageNum: number): Promise<void>;
    insertBlankPageFromThumb(where: 'before' | 'after'): void;
    deletePageFromThumb(): void;
    movePageUp(): Promise<void>;
    movePageDown(): Promise<void>;
    private swapPages;
    private ensurePage;
    private getPdfCanvas;
    private getAnnotCanvas;
    onViewerScroll(event: Event): void;
    prevPage(): Promise<void>;
    zoomIn(): Promise<void>;
    nextPage(): Promise<void>;
    firstPage(): Promise<void>;
    lastPage(): Promise<void>;
    zoomOut(): Promise<void>;
    scrollToPage(pageNum: number): void;
    scrollThumbnailIntoView(pageNum: number): void;
    private debouncedRenderVisible;
    renderAllPages(): Promise<void>;
    private lastParentWidth;
    private lastFitPageNo;
    /** Compute zoom so the WIDEST page in the document fits within the container.
     *  This prevents landscape pages from overflowing and being clipped by overflow-x. */
    fitWidth(): Promise<void>;
    private renderPage;
    private resizeAnnotCanvasTo;
    private setupResizeAutoRender;
    setToolMode(mode: ToolMode): void;
    updateCursor(): void;
    changeBrushSize(delta: number): void;
    setBrushColor(color: string): void;
    changeHighlightSize(delta: number): void;
    setHighlightColor(color: string): void;
    changeTextFontSize(delta: number): void;
    toggleDraw(): void;
    toggleEraser(): void;
    toggleHighlight(): void;
    enableTextPlaceMode(): void;
    toggleShapeMenu(): void;
    toggleShapeDropdown(): void;
    selectShape(type: 'rect' | 'circle' | 'arrow' | 'line'): void;
    setShapeStrokeColor(color: string): void;
    setShapeFillColor(color: string): void;
    toggleShapeFill(): void;
    toggleShapeNoStroke(): void;
    changeShapeStrokeSize(delta: number): void;
    private getNormPos;
    private finalizeActiveStroke;
    removeShapeStamp(id: string): void;
    startShapeDrag(e: PointerEvent, ssid: string): void;
    startShapeResize(ev: PointerEvent, shapeId: string, direction?: ResizeDirection): void;
    /** Returns arrow rotation angle in degrees — used in SVG template to avoid Math in template */
    getArrowAngleDeg(ss: any): number;
    onCanvasPointerDown(e: PointerEvent, p: number): void;
    onCanvasPointerMove(e: PointerEvent, p: number): void;
    onCanvasPointerUp(e: PointerEvent, p: number): void;
    private placeSignatureOnPage;
    /** Generate SHA-256 based Digital ID from userId */
    private hashUserId;
    /** Log signature placement to database for reference/audit */
    private logSignatureToDatabase;
    private placeTextBoxOnPage;
    changeEraserSize(delta: number): void;
    private eraseAtPoint;
    private calcLineWidth;
    private redraw;
    private drawStroke;
    private drawStrokeIncremental;
    private drawShape;
    canUndo(): boolean;
    canRedo(): boolean;
    undo(): void;
    redo(): void;
    clearAnnotations(): void;
    selectTextBox(id: string, ev: PointerEvent): void;
    onTextBoxPointerDown(ev: PointerEvent, id: string): void;
    clearTextSelection(): void;
    private getDragCanvasRect;
    startDrag(e: PointerEvent, textBoxId: string): void;
    startTextBoxDrag(ev: PointerEvent, textBoxId: string): void;
    onTextBoxInput(event: Event, tb: TextBox): void;
    onTextBoxFocus(id: string): void;
    startResize(ev: PointerEvent, textBoxId: string): void;
    startResizeRight(ev: PointerEvent, textBoxId: string): void;
    startResizeLeft(ev: PointerEvent, textBoxId: string): void;
    removeTextBox(textBoxId: string): void;
    private clampOneTextBox;
    private clampTextBoxesToView;
    triggerImageUpload(): void;
    private normalizeImageToPng;
    onImageSelected(event: Event): void;
    startImageDrag(e: PointerEvent, imgId: string): void;
    startImageResize(ev: PointerEvent, imageId: string, direction?: ResizeDirection): void;
    removeImage(imageId: string): void;
    openSignaturePad(): void;
    closeSignaturePad(): void;
    setSignaturePenColor(color: string): void;
    changeSignaturePenSize(delta: number): void;
    private initSignatureCanvas;
    private boundOnSigStart;
    private boundOnSigMove;
    private boundOnSigEnd;
    private getSignaturePos;
    private onSignatureStart;
    private onSignatureMove;
    private onSignatureEnd;
    private redrawSignatureCanvas;
    private drawBezierStroke;
    clearSignaturePad(): void;
    /** Render strokes at high resolution on an offscreen canvas and auto-crop */
    private trimSignatureCanvas;
    saveSignature(): void;
    startSignatureDrag(e: PointerEvent, sigId: string): void;
    startSignatureResize(ev: PointerEvent, sigId: string, direction?: ResizeDirection): void;
    removeSignature(sigId: string): void;
    openSignaturePickerOrPad(): void;
    closeSignaturePicker(): void;
    loadSavedSignatures(): Promise<void>;
    saveSignatureToDatabase(signatureName?: string): Promise<void>;
    useSavedSignature(sig: SavedSignature): void;
    presentToast(msg: string): Promise<void>;
    private placeSignatureOnCanvas;
    deleteSavedSignature(sig: SavedSignature, event?: Event): Promise<void>;
    setDefaultSignature(sig: SavedSignature, event?: Event): Promise<void>;
    openSignaturePadFromPicker(): void;
    triggerSignatureUpload(): void;
    onSignatureFileSelected(event: Event): Promise<void>;
    private removeWhiteBackground;
    enableFormFieldMode(type: 'text' | 'checkbox' | 'radio'): void;
    getFormFieldsForPage(page: number): PdfFormField[];
    removeFormField(id: string): void;
    startFormFieldDrag(e: PointerEvent, id: string): void;
    startMarkDrag(e: PointerEvent, markId: string): void;
    startFormFieldResize(e: PointerEvent, id: string, dir: ResizeDirection): void;
    changeFormFieldFontSize(id: string, delta: number): void;
    changeFormFieldSize(id: string, delta: number): void;
    toggleFormFieldBorder(id: string): void;
    enableMarkMode(type: 'check' | 'cross' | 'dot'): void;
    setMarkColor(color: string): void;
    changeMarkSize(delta: number): void;
    changeMarkStampSize(id: string, delta: number): void;
    generateMarkDataUrl(type: 'check' | 'cross' | 'dot', color: string, sizePx: number): string;
    addDateStamp(): void;
    startDateDrag(ev: PointerEvent, dateId: string): void;
    removeDateStamp(dateId: string): void;
    toggleBold(): void;
    toggleItalic(): void;
    setAlign(a: 'left' | 'center' | 'right'): void;
    setTextColor(color: string): void;
    exportDrawingJson(): string;
    private renderOverlayToPngBytes;
    private getPdfPlacement;
    saveDocument(): Promise<void>;
    generatePreviewPages(): Promise<void>;
    loadAllPreviewPages(): Promise<void>;
    confirmSave(): void;
    backToEdit(): void;
}
export {};
